//! SQL migration generator: JSON Schema -> SQL migration files.
//!
//! Generates up/down SQL migrations for schema changes, tracking versions
//! and supporting SQLite, PostgreSQL, and MySQL dialects.

use std::path::Path;
use chrono::Utc;

/// SQL dialect.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SqlDialect {
    SQLite,
    PostgreSQL,
    MySQL,
}

/// Migration direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MigrationDirection {
    Up,
    Down,
}

/// Migration file metadata.
#[derive(Debug, Clone)]
pub struct Migration {
    pub version: String,
    pub name: String,
    pub description: String,
    pub up_sql: String,
    pub down_sql: String,
}

/// Generate SQL migrations for a schema definition.
pub fn generate_migrations(
    schema: &dt_schema::SchemaDef,
    dialect: SqlDialect,
    out_dir: &Path,
) -> Result<Migration, dt_core::DTError> {
    let timestamp = Utc::now().format("%Y%m%d%H%M%S").to_string();
    let version = format!("{}_{}", timestamp, sanitize_ident(&schema.name));
    let name = schema.name.clone();
    let description = schema.description.clone();
    
    let (up_sql, down_sql) = generate_migration_sql(schema, dialect)?;
    
    let migration = Migration {
        version: version.clone(),
        name,
        description,
        up_sql,
        down_sql,
    };
    
    // Write up migration
    let up_path = out_dir.join(format!("{}_up.sql", version));
    std::fs::write(&up_path, &migration.up_sql)?;
    
    // Write down migration
    let down_path = out_dir.join(format!("{}_down.sql", version));
    std::fs::write(&down_path, &migration.down_sql)?;
    
    Ok(migration)
}

/// Generate up/down SQL for a schema.
fn generate_migration_sql(
    schema: &dt_schema::SchemaDef,
    dialect: SqlDialect,
) -> Result<(String, String), dt_core::DTError> {
    let table_name = sanitize_ident(&schema.name);
    
    // Extract properties from schema
    let columns = extract_columns(schema, dialect)?;
    
    let up_sql = generate_create_table(&table_name, &columns, dialect);
    let down_sql = generate_drop_table(&table_name, dialect);
    
    Ok((up_sql, down_sql))
}

/// Extract column definitions from schema.
fn extract_columns(
    schema: &dt_schema::SchemaDef,
    dialect: SqlDialect,
) -> Result<Vec<Column>, dt_core::DTError> {
    let mut columns = Vec::new();
    
    // Add id column
    columns.push(Column {
        name: "id".to_string(),
        sql_type: get_id_type(dialect),
        nullable: false,
        primary_key: true,
        default: None,
    });
    
    // Extract properties
    if let Some(props) = schema.parsed.get("properties").and_then(|v| v.as_object()) {
        for (key, val) in props {
            let sql_type = json_type_to_sql(val, dialect);
            let nullable = !is_required(key, &schema.parsed);
            
            columns.push(Column {
                name: sanitize_ident(key),
                sql_type,
                nullable,
                primary_key: false,
                default: None,
            });
        }
    }
    
    // Add metadata columns
    columns.push(Column {
        name: "created_at".to_string(),
        sql_type: get_timestamp_type(dialect),
        nullable: false,
        primary_key: false,
        default: Some(get_current_timestamp_default(dialect)),
    });
    
    columns.push(Column {
        name: "updated_at".to_string(),
        sql_type: get_timestamp_type(dialect),
        nullable: false,
        primary_key: false,
        default: Some(get_current_timestamp_default(dialect)),
    });
    
    Ok(columns)
}

/// Column definition.
#[derive(Debug, Clone)]
struct Column {
    name: String,
    sql_type: String,
    nullable: bool,
    primary_key: bool,
    default: Option<String>,
}

/// Generate CREATE TABLE statement.
fn generate_create_table(table_name: &str, columns: &[Column], dialect: SqlDialect) -> String {
    let mut lines = Vec::new();
    
    lines.push(format!("-- Migration: create table {}", table_name));
    lines.push(format!("-- Generated by dt-codegen"));
    lines.push("".to_string());
    lines.push(format!("CREATE TABLE IF NOT EXISTS {} (", table_name));
    
    let column_defs: Vec<String> = columns
        .iter()
        .map(|col| {
            let mut parts = vec![format!("    {}", col.name)];
            parts.push(col.sql_type.clone());
            
            if col.primary_key {
                parts.push("PRIMARY KEY".to_string());
            }
            
            if !col.nullable && !col.primary_key {
                parts.push("NOT NULL".to_string());
            }
            
            if let Some(default) = &col.default {
                parts.push(format!("DEFAULT {}", default));
            }
            
            parts.join(" ")
        })
        .collect();
    
    lines.push(column_defs.join(",\n"));
    lines.push(");".to_string());
    
    // Add indexes for common columns
    if dialect == SqlDialect::PostgreSQL || dialect == SqlDialect::MySQL {
        lines.push("".to_string());
        lines.push(format!("CREATE INDEX IF NOT EXISTS idx_{}_created_at ON {} (created_at);", table_name, table_name));
        lines.push(format!("CREATE INDEX IF NOT EXISTS idx_{}_updated_at ON {} (updated_at);", table_name, table_name));
    }
    
    lines.join("\n")
}

/// Generate DROP TABLE statement.
fn generate_drop_table(table_name: &str, dialect: SqlDialect) -> String {
    let mut lines = Vec::new();
    
    lines.push(format!("-- Migration: drop table {}", table_name));
    lines.push("-- Generated by dt-codegen".to_string());
    lines.push("".to_string());
    
    match dialect {
        SqlDialect::SQLite => {
            lines.push(format!("DROP TABLE IF EXISTS {};", table_name));
        }
        SqlDialect::PostgreSQL | SqlDialect::MySQL => {
            lines.push(format!("DROP TABLE IF EXISTS {} CASCADE;", table_name));
        }
    }
    
    lines.join("\n")
}

/// Convert JSON type to SQL type.
fn json_type_to_sql(val: &serde_json::Value, dialect: SqlDialect) -> String {
    let t = val.get("type").and_then(|v| v.as_str()).unwrap_or("object");
    match t {
        "string" => {
            if val.get("format").and_then(|v| v.as_str()) == Some("date-time") {
                get_timestamp_type(dialect)
            } else if let Some(max_len) = val.get("maxLength").and_then(|v| v.as_u64()) {
                match dialect {
                    SqlDialect::SQLite => "TEXT".to_string(),
                    SqlDialect::PostgreSQL => format!("VARCHAR({})", max_len),
                    SqlDialect::MySQL => format!("VARCHAR({})", max_len),
                }
            } else {
                match dialect {
                    SqlDialect::SQLite => "TEXT".to_string(),
                    SqlDialect::PostgreSQL => "TEXT".to_string(),
                    SqlDialect::MySQL => "VARCHAR(255)".to_string(),
                }
            }
        }
        "integer" => match dialect {
            SqlDialect::SQLite => "INTEGER".to_string(),
            SqlDialect::PostgreSQL => "BIGINT".to_string(),
            SqlDialect::MySQL => "BIGINT".to_string(),
        },
        "number" => match dialect {
            SqlDialect::SQLite => "REAL".to_string(),
            SqlDialect::PostgreSQL => "DOUBLE PRECISION".to_string(),
            SqlDialect::MySQL => "DOUBLE".to_string(),
        },
        "boolean" => match dialect {
            SqlDialect::SQLite => "INTEGER".to_string(),
            SqlDialect::PostgreSQL => "BOOLEAN".to_string(),
            SqlDialect::MySQL => "TINYINT(1)".to_string(),
        },
        "array" => match dialect {
            SqlDialect::SQLite => "TEXT".to_string(), // JSON encoded
            SqlDialect::PostgreSQL => "JSONB".to_string(),
            SqlDialect::MySQL => "JSON".to_string(),
        },
        "object" => match dialect {
            SqlDialect::SQLite => "TEXT".to_string(), // JSON encoded
            SqlDialect::PostgreSQL => "JSONB".to_string(),
            SqlDialect::MySQL => "JSON".to_string(),
        },
        _ => match dialect {
            SqlDialect::SQLite => "TEXT".to_string(),
            SqlDialect::PostgreSQL => "TEXT".to_string(),
            SqlDialect::MySQL => "VARCHAR(255)".to_string(),
        },
    }
}

/// Get ID column type for dialect.
fn get_id_type(dialect: SqlDialect) -> String {
    match dialect {
        SqlDialect::SQLite => "TEXT PRIMARY KEY".to_string(),
        SqlDialect::PostgreSQL => "UUID PRIMARY KEY DEFAULT gen_random_uuid()".to_string(),
        SqlDialect::MySQL => "CHAR(36) PRIMARY KEY".to_string(),
    }
}

/// Get timestamp type for dialect.
fn get_timestamp_type(dialect: SqlDialect) -> String {
    match dialect {
        SqlDialect::SQLite => "TEXT".to_string(),
        SqlDialect::PostgreSQL => "TIMESTAMPTZ".to_string(),
        SqlDialect::MySQL => "TIMESTAMP".to_string(),
    }
}

/// Get current timestamp default for dialect.
fn get_current_timestamp_default(dialect: SqlDialect) -> String {
    match dialect {
        SqlDialect::SQLite => "(strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))".to_string(),
        SqlDialect::PostgreSQL => "NOW()".to_string(),
        SqlDialect::MySQL => "CURRENT_TIMESTAMP".to_string(),
    }
}

/// Check if a property is required.
fn is_required(key: &str, schema: &serde_json::Value) -> bool {
    schema
        .get("required")
        .and_then(|v| v.as_array())
        .map(|arr| arr.iter().any(|v| v.as_str() == Some(key)))
        .unwrap_or(false)
}

/// Sanitize identifier for SQL.
fn sanitize_ident(s: &str) -> String {
    s.replace("-", "_")
        .replace(".", "_")
        .replace(" ", "_")
        .to_lowercase()
}

#[cfg(test)]
mod tests {
    use super::*;
    use dt_schema::SchemaDef;
    use std::path::PathBuf;
    use tempfile::TempDir;

    #[test]
    fn test_generate_sqlite_migration() {
        let dir = TempDir::new().unwrap();
        let schema = SchemaDef {
            name: "users".into(),
            version: "1.0.0".into(),
            path: PathBuf::new(),
            raw: r#"{}"#.into(),
            parsed: serde_json::json!({
                "title": "User",
                "required": ["email"],
                "properties": {
                    "email": {"type": "string"},
                    "age": {"type": "integer"},
                    "active": {"type": "boolean"}
                }
            }),
            description: "User table".into(),
            codegen_targets: vec![],
        };
        
        let migration = generate_migrations(&schema, SqlDialect::SQLite, dir.path()).unwrap();
        assert!(migration.up_sql.contains("CREATE TABLE IF NOT EXISTS users"));
        assert!(migration.up_sql.contains("id TEXT PRIMARY KEY"));
        assert!(migration.up_sql.contains("email TEXT NOT NULL"));
        assert!(migration.down_sql.contains("DROP TABLE IF EXISTS users"));
    }

    #[test]
    fn test_generate_postgresql_migration() {
        let dir = TempDir::new().unwrap();
        let schema = SchemaDef {
            name: "posts".into(),
            version: "1.0.0".into(),
            path: PathBuf::new(),
            raw: r#"{}"#.into(),
            parsed: serde_json::json!({
                "title": "Post",
                "properties": {
                    "title": {"type": "string", "maxLength": 200},
                    "content": {"type": "string"},
                    "tags": {"type": "array"}
                }
            }),
            description: "Blog posts".into(),
            codegen_targets: vec![],
        };
        
        let migration = generate_migrations(&schema, SqlDialect::PostgreSQL, dir.path()).unwrap();
        assert!(migration.up_sql.contains("CREATE TABLE IF NOT EXISTS posts"));
        assert!(migration.up_sql.contains("UUID PRIMARY KEY DEFAULT gen_random_uuid()"));
        assert!(migration.up_sql.contains("VARCHAR(200)"));
        assert!(migration.up_sql.contains("JSONB"));
        assert!(migration.down_sql.contains("DROP TABLE IF EXISTS posts CASCADE"));
    }
}
