//! Python dataclass generator from JSON Schema.

use std::path::Path;

pub fn generate(
    schema: &dt_schema::SchemaDef,
    out_dir: &Path,
) -> Result<String, dt_core::DTError> {
    let module_name = sanitize_ident(&schema.name);
    let filename = format!("{}.py", module_name);
    let out_path = out_dir.join(&filename);

    let class_name = schema
        .parsed
        .get("title")
        .and_then(|v| v.as_str())
        .unwrap_or(&schema.name)
        .to_string();
    let class_name = snake_to_pascal(&class_name);

    let mut lines: Vec<String> = Vec::new();
    lines.push("# Generated by dt-codegen — DO NOT EDIT.".to_string());
    lines.push(format!("# Source: {} v{}", schema.name, schema.version));
    lines.push("from dataclasses import dataclass, field".to_string());
    lines.push("from typing import Optional, List, Dict, Any".to_string());
    lines.push("".to_string());
    lines.push(format!("@dataclass"));
    lines.push(format!("class {}:", class_name));

    if let Some(props) = schema.parsed.get("properties").and_then(|v| v.as_object()) {
        for (key, val) in props {
            let field_type = json_type_to_python(val);
            let optional = !is_required(key, &schema.parsed);
            let anno = if optional {
                format!("Optional[{}] = None", field_type)
            } else {
                field_type
            };
            lines.push(format!("    {}: {}", key, anno));
        }
    }

    let source = lines.join("\n");
    std::fs::write(&out_path, &source)?;

    Ok(out_path.to_string_lossy().to_string())
}

fn sanitize_ident(s: &str) -> String {
    s.replace("-", "_")
        .replace(".", "_")
        .replace(" ", "_")
}

fn snake_to_pascal(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn json_type_to_python(val: &serde_json::Value) -> String {
    let t = val.get("type").and_then(|v| v.as_str()).unwrap_or("object");
    match t {
        "string" => "str".into(),
        "integer" => "int".into(),
        "number" => "float".into(),
        "boolean" => "bool".into(),
        "array" => "List[Any]".into(),
        "object" => "Dict[str, Any]".into(),
        _ => "Any".into(),
    }
}

fn is_required(key: &str, schema: &serde_json::Value) -> bool {
    schema
        .get("required")
        .and_then(|v| v.as_array())
        .map(|arr| arr.iter().any(|v| v.as_str() == Some(key)))
        .unwrap_or(false)
}
