//! Rust code generator: JSON Schema -> struct definitions.

use std::path::Path;

/// Generate a Rust module from a schema definition.
pub fn generate(
    schema: &dt_schema::SchemaDef,
    out_dir: &Path,
) -> Result<String, dt_core::DTError> {
    let module_name = sanitize_ident(&schema.name);
    let filename = format!("{}.rs", module_name);
    let out_path = out_dir.join(&filename);

    let mut lines: Vec<String> = Vec::new();
    lines.push("// Generated by dt-codegen — DO NOT EDIT.".to_string());
    lines.push(format!("// Source: {} v{}", schema.name, schema.version));
    lines.push("use serde::{Deserialize, Serialize};".to_string());
    lines.push("".to_string());

    // Derive name from schema title or name
    let struct_name = schema
        .parsed
        .get("title")
        .and_then(|v| v.as_str())
        .unwrap_or(&schema.name)
        .to_string();
    let struct_name = sanitize_ident(&struct_name);

    lines.push(format!("#[derive(Debug, Clone, Serialize, Deserialize)]"));
    lines.push(format!("pub struct {} {{", struct_name));

    // Walk properties
    if let Some(props) = schema.parsed.get("properties").and_then(|v| v.as_object()) {
        for (key, val) in props {
            let field_name = sanitize_ident(key);
            let field_type = json_type_to_rust(val);
            let optional = !is_required(key, &schema.parsed);
            let type_str = if optional {
                format!("Option<{}>", field_type)
            } else {
                field_type
            };
            lines.push(format!("    pub {}: {},", field_name, type_str));
        }
    }

    lines.push("}".to_string());

    let source = lines.join("\n");
    std::fs::write(&out_path, &source)?;

    Ok(out_path.to_string_lossy().to_string())
}

fn sanitize_ident(s: &str) -> String {
    let mut out = s
        .replace("-", "_")
        .replace(".", "_")
        .replace(" ", "_");
    if out.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        out = format!("_{}", out);
    }
    out
}

fn json_type_to_rust(val: &serde_json::Value) -> String {
    let t = val.get("type").and_then(|v| v.as_str()).unwrap_or("object");
    match t {
        "string" => {
            if val.get("format").and_then(|v| v.as_str()) == Some("date-time") {
                "String".into() // Could be chrono::DateTime later
            } else {
                "String".into()
            }
        }
        "integer" => "i64".into(),
        "number" => "f64".into(),
        "boolean" => "bool".into(),
        "array" => "Vec<serde_json::Value>".into(),
        "object" => {
            if val.get("additionalProperties").and_then(|v| v.as_bool()) == Some(true) {
                "std::collections::HashMap<String, serde_json::Value>".into()
            } else {
                "serde_json::Value".into()
            }
        }
        _ => "serde_json::Value".into(),
    }
}

fn is_required(key: &str, schema: &serde_json::Value) -> bool {
    schema
        .get("required")
        .and_then(|v| v.as_array())
        .map(|arr| arr.iter().any(|v| v.as_str() == Some(key)))
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use dt_schema::SchemaDef;
    use std::path::PathBuf;
    use tempfile::TempDir;

    #[test]
    fn test_generate_rust_struct() {
        let dir = TempDir::new().unwrap();
        let schema = SchemaDef {
            name: "test_event".into(),
            version: "1.0.0".into(),
            path: PathBuf::new(),
            raw: r#"{}"#.into(),
            parsed: serde_json::json!({
                "title": "TestEvent",
                "required": ["id"],
                "properties": {
                    "id": {"type": "string"},
                    "count": {"type": "integer"}
                }
            }),
            description: "".into(),
            codegen_targets: vec!["rust".into()],
        };
        let path = generate(&schema, dir.path()).unwrap();
        assert!(path.contains("test_event.rs"));
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("pub struct TestEvent"));
        assert!(content.contains("pub id: String,"));
        assert!(content.contains("pub count: Option<i64>,"));
    }
}
